version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
        - SERVER_URL=${SERVER_URL}
    container_name: metis-frontend
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.metis-frontend.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.metiss.ch`, `metiss.ch`) && !PathPrefix(`/api`)'
      - 'traefik.http.routers.metis-frontend.entrypoints=websecure'
      - 'traefik.http.routers.metis-frontend.tls=true'
      - 'traefik.http.routers.metis-frontend.tls.certresolver=letsencrypt'
      - 'traefik.http.services.metis-frontend.loadbalancer.server.port=80'

networks:
  traefik-network:
    external: true
